version: '3.8'

x-celery-env: &celery-env
  CELERY_BROKER_URL: amqp://gpuphot:gpuphot@rabbitmq:5672/
  CELERY_RESULT_BACKEND: redis://redis:6379/0

x-common-worker-backend: &common-worker-backend
  build:
    context: .
    dockerfile: Dockerfile
    target: worker
  env_file:
    - path: ./.env
      required: false
  environment:
    <<: *celery-env
    INSTRUMENT_NAME: ${INSTRUMENT_NAME:-default}
    GPU_ID: ${GPU_ID:-0}
    POSTGRES_DB: GPUPhotDB
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gpuphot}
    INSTRUMENT_CONFIG_BASE_PATH: /data/instrument_configs
    IMAGE_BASE_PATH: /data/images
  volumes:
    - ${INSTRUMENT_CONFIG_PATH:-./gpuphot/instrument_configs}:/gpuphot/instrument_configs:z
    - ${IMAGE_PATH:-~/gpuphot_images}:/data/images:z
    - ${ASTROMETRY_CACHE_PATH:-./astrometry_cache}:/data/astrometry_cache:z
    - /run/docker.sock:/run/docker.sock
  depends_on:
    - rabbitmq
    - redis
  restart: unless-stopped

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: gpuphot
      RABBITMQ_DEFAULT_PASS: gpuphot
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  beat:
    <<: *common-worker-backend
    command: ["celery", "-A", "gpuphot_worker.worker_app", "beat"]

  gpuphot_worker:
    <<: *common-worker-backend
    command: [ "celery", "-A", "gpuphot_worker.worker_app", "worker", "-c", "${CELERY_CONCURRENCY:-1}", "-n", "gpuphot-worker-${GPU_ID:-0}", "--soft-time-limit", "240", "--time-limit", "300" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "${GPU_ID:-0}" ]
              capabilities: [ gpu ]

  lab:
    build:
      context: .
      dockerfile: Dockerfile
      target: lab
    env_file:
      - path: ./.env
        required: false
    ports:
      - "8888:8888"
    environment:
      <<: *celery-env
      JUPYTER_ENABLE_LAB: "yes"
      INSTRUMENT_NAME: ${INSTRUMENT_NAME:-default}
      INSTRUMENT_CONFIG_BASE_PATH: /data/instrument_configs
      IMAGE_BASE_PATH: /data/images
    volumes:
      - ./notebooks:/home/jovyan/work:z
      - ${INSTRUMENT_CONFIG_PATH:-./gpuphot/instrument_configs}:/data/instrument_configs:z
      - ${IMAGE_PATH:-~/gpuphot_images}:/data/images:z
      - ${ASTROMETRY_CACHE_PATH:-astrometry_cache}:/data/astrometry_cache:z
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    restart: unless-stopped

  flower:
    build:
      context: .
      dockerfile: Dockerfile
      target: flower
    environment:
      <<: *celery-env
      NVIDIA_VISIBLE_DEVICES: "none"
      NVIDIA_DRIVER_CAPABILITIES: ""
      FLOWER_PORT: 5555
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis
    command: [ "celery", "-A", "gpuphot_worker.worker_app", "flower" ]
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: Dockerfile
      target: q3c_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: GPUPhotDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gpuphot}
    volumes:
      - ./gpuphot_database:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

  profiler:
    build:
      context: .
      dockerfile: Dockerfile
      target: profiler
      args:
        - ROOT_PASSWORD=${ROOT_PASSWORD:-gpuphot_profiler}
        - SSSH_PORT=${PROFILER_SSSH_PORT:-2222}
    profiles: ["debug"]
    environment:
      <<: *celery-env
      INSTRUMENT_NAME: ${INSTRUMENT_NAME:-default}
      GPU_ID: ${GPU_ID:-0}
      POSTGRES_DB: GPUPhotDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gpuphot}
      INSTRUMENT_CONFIG_BASE_PATH: /data/instrument_configs
      IMAGE_BASE_PATH: /data/images
    volumes:
      - ${INSTRUMENT_CONFIG_PATH:-./gpuphot/instrument_configs}:/data/instrument_configs:z
      - ${IMAGE_PATH:-~/gpuphot_images}:/data/images:z
      - ${ASTROMETRY_CACHE_PATH:-./astrometry_cache}:/data/astrometry_cache:z
      - ${PROFILER_RESULTS_PATH:-./profiling_results}:/app/profiling_results:z
    ports:
      - "${PROFILER_SSSH_PORT:-2222}:22"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "${GPU_ID:-0}" ]
              capabilities: [ gpu ]
    stdin_open: true
    tty: true

