[metadata]
name = GPUPhot
version = attr: gpuphot.__version__
author = Samuel Lemes Perera
author_email = Samuel@lightbridges.es
description = GPU photometry library
long_description = file: README.md
long_description_content_type = text/markdown
url = https://lightbridges.es/
keywords = gpu, photometry
license = BSD 3-Clause License
classifiers =
    License :: OSI Approved :: BSD License
    Programming Language :: Python :: 3

[options]
packages = find:
zip_safe = True
include_package_data = True
python_requires = >=3.10
install_requires = file: requirements.txt
;     numpy==1.26.1
;     astropy==5.3.4
;     astroquery==0.4.6
;     pandas==1.3.5
;     pytz==2022.1
;     cupy==12.2.0
;     astrometry==4.1.2
;     tensorflow==2.14.0
;     scikit-learn==1.3.2
;     keras==2.14.0
;     astroalign==2.5.1
;     scikit-image==0.22.0

[options.extras_require]
test =
    pytest
;
; [options.entry_points]
; console_scripts =
;     # Add any console scripts here

