HEADER_DESCRIPTIONS = {
    'BITPIX': 'Bits that represent a data value (8,16,32,-32,-64)',
    'COMODE': 'Color mode',
    'DIAMETER': '[mm] Telescope diameter',
    'DRMODE': 'Dynamic range mode',
    'EXPTI': '[s] Exposure time of sub-frame',
    'EXPTIME': '[s] Total exposure time',
    'FILTER': 'Filter used',
    'FOCAL': 'Telescope focal ratio',
    'FOCALEN': '[mm] Telescope focal length',
    'FWHMORI': '[px] Reference FWHM of stars in the image',
    'GAIN': '[e/ADU] Gain',
    'GAINHIGH': '[e/ADU] Gain in high mode',
    'GAINLOW': '[e/ADU] Gain in low mode',
    'GAMODE': 'Gain mode',
    'IMAGETYP': 'Type of image',
    'INFIRMW': 'Instrument firmware version',
    'INMODEL': 'Instrument model',
    'INSDK': 'Instrument SDK version',
    'INSERIAL': 'Instrument serial number',
    'INSTRUME': 'Instrument',
    'BIASTEMP': '[C] Instrument temperature of MasterBias',
    'DARKTEMP': '[C] Instrument temperature of MasterDark',
    'FLATTEMP': '[C] Instrument temperature of MasterFlat',
    'BIASMEAN': '[ADU] MasterBias mean',
    'DARKMEAN': '[ADU/s] Mean of the MasterDark frame',
    'FLATMEAN': '[ADU] Mean of the MasterFlat frame',
    'OVERMED': 'Median of overscan region, in ADU',
    'MPCCODE': 'MPC code',
    'OBJECT': 'Object',
    'OBS': 'Observatory',
    'OFFSET': '[ADU] Pedestal level',
    'PARITY': 'Image parity',
    'POINTDEC': '[deg] Declination (J2000) sent to telescope',
    'POINTRA': '[h] Right ascension (J2000) sent to telescope',
    'PXSIZE': '[um] Pixel size',
    'RDMODE': 'Readout mode',
    'RDNOISE': '[e] Readout noise',
    'READOUT': '[MHz] Readout rate',
    'SATLEVEL': '[ADU] Saturation level',
    'SCALE': '[arcsec/px] Calculated plate scale',
    'SCALEERR': '[arcsec/px] Nominal plate scale uncertainty',
    'SCALEORI': '[arcsec/px] Nominal plate scale',
    'SEXPTIME': '[s] Exposure time of each sub-frame',
    'SHMODE': 'Electronic shutter mode',
    'SITEELEV': '[m] Telescope elevation',
    'SITELAT': '[deg] Telescope latitude',
    'SITELONG': '[deg] Telescope longitude',
    'BIASN': 'Number of stacked frames in MasterBias',
    'DARKN': 'Number of staked frames in MasterDark',
    'FLATN': 'Number of staked frames in MasterFlat',
    'STACKIMA': 'Number of staked frames',
    'STDCLIP': 'Lower and upper sigma clipping in stacking',
    'DARKSTD': '[ADU/s] MasterDark standard deviation',
    'FLATSTD': '[ADU] Standard deviation in flat stacking',
    'OVERSTD': '[ADU] Std of overscan region',
    'TELESCOP': 'Telescope name',
    'TRIGGER': 'Type of trigger',
    'UTB': '[UTC] Date of MasterBias creation',
    'UTD': '[UTC] Date of MasterDark creation',
    'FLATDATE': '[UTC] Date of capture of MasterFlat',
    'UTI': '[UTC] Datetime of sub-frame',
    'WORKTEMP': '[C] Instrument temperature',
    'XBINNING': 'Binning in X axis',
    'YBINNING': 'Binning in Y axis',
    'INTEMP': '[C] Instrument temperature',
    'OVERSCSX': 'Overscan region origin in X axis',
    'OVERSCNX': 'Overscan region lines in X axis',
    'OVERSCSY': 'Overscan region origin in Y axis',
    'OVERSCNY': 'Overscan region lines in Y axis',
    'EFFECTSX': 'Effective region origin in X axis',
    'EFFECTNX': 'Effective region lines in X axis',
    'EFFECTSY': 'Effective region origin in Y axis',
    'EFFECTNY': 'Effective region lines in Y axis',
    'STATSX': 'Stats region origin in X axis',
    'STATNX': 'Stats region lines in X axis',
    'STATSY': 'Stats region origin in Y axis',
    'STATNY': 'Stats region lines in Y axis',
    'DC': '[e/s] Nominal dark current',
    'DATE-OBS': '[UTC] Beginning of the capture',
    'HUMIDITY': '[%] Relative humidity',
    'AMBTEMP': '[C] Ambient temperature',
    'WINDDIR': '[deg] Wind direction',
    'WINDVEL': '[m/s] Wind speed',
    'DUSTPM10': '[ug/m3] Particle matter density <10 micron',
    'DUSTPM25': '[ug/m3] Particle matter density <2.5 micron',
    'DUSTPM1': '[ug/m3] Particle matter density <1 micron',
    'CLOUD': 'Cloud presence, 0 = Clear, 1 = Cloudy',
    'PRESSURE': '[mbar] Local pressure',
    'DEWPOINT': '[C] Dew point',
    'DUSTPLA': '[PLA/m3] Dust, in Polystyrol-Latex-Aerosols',
    'PWV': '[mm] Precipitable water vapour',
    'ILLUMINA': '[lux] Solar illuminance',
    'TESSMAG': '[mag/arcsec2] TESS-W cenital sky brightness',
    'SKYIRTEM': '[C] IR cenital sky temperature',
    'BIASSTD': '[ADU] MasterBias standard deviation',
    'DATE': '[UTC] Date of file creation',
    'BIASDATE': '[UTC] Date of capture of MasterBias',
    'BIASCORR': 'Bias correction method',
    'BIASOVER': '[ADU] Median level in MasterBias overscan',
    'WINDOWSX': 'Window region origin in X axis',
    'WINDOWSY': 'Window region origin in Y axis',
    'WINDOWNX': 'Window region lines in X axis',
    'WINDOWNY': 'Window region lines in Y axis',
    'FWHMI': '[px] Full-width half maximum of sub-frame',
    'FWHMMED': '[px] Median FWHM in the subframes center',
    'FWHMSTD': '[px] Std. FWHM in the subframes center',
    'FOCUS': '[um] Focuser position',
    'HSSPEED': '[MHz] Horizontal shift speed (readout rate)',
    'VSSPEED': '[us/line] Vertical shift speed',
    'PREAMPGA': 'Pre Amp gain factor',
    'MIRRTEMP': '[C] Telescope mirror temperature',
    'MIRRHUM': '[%] Telescope mirror relative humidity',
    'DARKDATE': '[UTC] Date of capture of MasterDark',
    'RA-MNT': '[deg] Central right ascension',
    'DEC': '[deg] Central declination',
    'RAhms': '[hh:mm:ss] Central Right ascension',
    'DECdms': '[dd:mm:ss] Central declination',
    'AZ': '[deg] Azimut',
    'ALT': '[deg] Altitude',
    'ZD': '[deg] Zenital distance, in degrees',
    'AIRMASS': 'Airmass',
    'LONGAL': '[deg] Galactic longitude',
    'LATGAL': '[deg] Galactic latitude',
    'LONECL': '[deg] Baricentric mean ecliptic longitude',
    'LATECL': '[deg] Baricentric mean ecliptic latitude',
    'SITENAME': 'Telescope site name',
    'SITECODE': 'Telescope IAU Code',
    'MOUNT': 'Mount type',
    'CAMERA': 'Camera name',
    'COOLERST': 'Cooler status',
    'SEQNUM': 'Number in the sequence',
    'JD': 'Julian date',
    'MJD': 'Modified julian date',
    'GPSDAT': '[UTC] Beginning of capture from the GPS',
    'GPSLAT': '[deg] Latitude measured by the GPS',
    'GPSLON': '[deg] Longitude measured by the GPS',
    'PCDATE': '[UTC] Beginning of capture from the PC',
    'UTOBS': '[UTC] Mean datetime of observation',
    'INTEGT': '[s] Sum of all exposition times',
    'TOTIMA': 'Number of captures for this image',
    'OBLINEID': 'ObservingBlockLine ID',
    'DARKMIN': '[ADU] Minimum of the MasterDark frame',
    'DARKMAX': '[ADU] Maximum of the MasterDark frame',
    'OBID': 'ObservingBlock ID',
    'ORID': 'ObservingRun ID',
    'ORISIZEX': 'Number of pixels in axis X',
    'ORISIZEY': 'Number of pixels in axis Y',
    'ALISIZEX': 'Image xsize for aligning, centered',
    'ALISIZEY': 'Image ysize for aligning, centered',
    'FINSIZEX': 'Image xsize for final saved image, centered',
    'FINSIZEY': 'Image ysize for final saved image, centered',
    'ROT': '[deg] Alignment rotation',
    'SHX': '[px] Alignment shift in X axis',
    'SHY': '[px] Alignment shift in Y axis',
    'ZOO': 'Alignment scaling',
    'FC': 'Alignment flux correction',
    'JD-OBS': 'Julian date',
    'MJD-OBS': 'Modified julian date',
    'DEC-MNT': '[deg] Central declination',
    'RA': '[deg] Central right ascension',
    'HSYNC': '[us] Time difference between rows',
    'SITEALT': '[m] Telescope elevation',
    'CCW': '[deg] Field rotation counterclockwise',
    'FOVX': '[arcmin] Field of view in x axis',
    'FOVY': '[arcmin] Field of view in y axis',
    'ZP': '[ADU/s] Zeropoint',
    'EZP': '[ADU/s] Zeropoint uncertainty (1-sigma)',
    'SLOPE': 'Calibration slope',
    'ESLOPE': 'Calibration slope uncertainty',
    'CATALOG': 'Photometric catalog used in calibration',
    'CATBAND': 'Catalog passband',
    'CATNSTAR': 'Number of stars used in ZP',
    'APERRAD': '[px] Aperture radius',
    'FWHM': '[px] FWHM in the center of the image',
    'FWHMLL': '[px] FWHM in the lower-left corner',
    'FWHMLR': '[px] FWHM in the lower-right corner',
    'FWHMUR': '[px] FWHM in the upper-right corner',
    'FWHMUL': '[px] FWHM in the upper-left corner',
    'MAGLIM': '[mag] 3-sigma limiting magnitude',
    'FLUXSKY': '[ADU/px] Median sky flux per pixel',
    'OBJECSNR': 'Target signal-to-noise ratio',
    'ZPMINMAG': '[mag] Brightest star magnitude for ZP',
    'ZPMAXMAG': '[mag] Faintest star magnitude for ZP',
    'APINTER': '[px] Aperture radius function intercept',
    'APSLOPE': '[px/log10(snr)] Aperture radius slope',
    'DATEPROC': '[UTC] Date when the file was processed',
    'BVMIN': '[B-V] Minimum color for ZP stars',
    'BVMAX': '[B-V] Maximum color for ZP stars',
    'MOONALT': '[deg] Moon altitude',
    'MOONAZ': '[deg] Moon azimut',
    'MOONDIST': '[deg] Distance to Moon',
    'MOONILUM': '[%] Moon illumination',
    'SUNALT': '[deg] Sun altitude',
    'SUNAZ': '[deg] Sun azimut',
    'RAPREC': '[arcsec] RA precision of detected sources',
    'DECPREC': '[arcsec] DEC precision of detected sources',
    'RADISP': '[arcsec] RA dispersion of detected sources',
    'DECDISP': '[arcsec] DEC dispersion of detected sources',
    'RAD10': '[px] Aperture radius for stars with SNR = 10',
    'RAD100': '[px] Aperture radius for stars with SNR = 100',
    'RAD1000': '[px] Aperture radius for stars with SNR = 1000',
    'RAD5000': '[px] Aperture radius for stars with SNR = 5000',
    'CORR10': 'Aperture correction factor for SNR = 10',
    'CORR100': 'Aperture correction factor for SNR = 100',
    'CORR1000': 'Aperture correction factor for SNR = 1000',
    'CORR5000': 'Aperture correction factor for SNR = 5000',
    'GPUPHOTI': 'GPUPhot Unique identifier'
}
